# Generated by Django 4.0.2 on 2022-02-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='default_sprite',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='shiny_sprite',
            field=models.CharField(max_length=150),
        ),
    ]
